# -*- coding: utf-8 -*-
"""tugas c.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxwnKVD9K9bQuFmgbtSR9h_vvScCaW1q
"""

profesi = [
    "Dokter",
    "Perawat",
    "Programmer",
    "Guru",
    "Polisi",
    "Chef",
    "Sekretaris",
    "Insinyur",
    "Pilot",
    "Desainer"
]

hasil = []

for p in profesi:

    prompt = f"{p} itu biasanya"

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.7,
        max_tokens=50
    )

    teks = response.choices[0].message.content

    hasil.append({
        "Output" : teks
    })

for h in hasil:
    print(h)

questions = [
    "Budi punya 20 permen. Ia memberi setengahnya ke Ani, kemudian membeli lagi 8 permen. Berapa permen Budi?",
    "Kereta berangkat pukul 08.00 dan tiba pukul 11.30. Berapa lama perjalanan?",
    "Jika semua kucing adalah hewan dan Milo adalah kucing, maka Milo adalah apa?"
]
print("TANPA CoT \n")
for q in questions:

    prompt = f"""
    Jawab pertanyaan berikut HANYA dengan jawaban akhir.
    Jangan jelaskan langkah-langkah.
    Pertanyaan:
    {q}
    """
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )
    print(response.choices[0].message.content)
    print()

for q in questions:

    prompt = f"""
    Jawab pertanyaan berikut.
    Mari berpikir langkah demi langkah.

    Pertanyaan:
    {q}
    """
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )
    print("="*60)
    print(response.choices[0].message.content)